### ISSUE TITLE
support `order by rowid` efficiently

### ISSUE THREAD

**Issue by cldellow** [cldellow/sqlite-parquet-vtable#11]
https://github.com/simonw/datasette is a nifty tool that lets you expose a web UI/REST API for querying SQLite DBs.

Currently, though, you have to launch it via:

```
datasette serve db.db --load-extension /home/cldellow/src/parquet-vtable/parquet/libparquet.so --config sql_time_limit_ms:350000
```

ie give it an extra long timeout. This is because it's default screen does queries like:

```
select * from tablename where rowid > N order by rowid limit 1000
```

We don't currently guarantee ordering, so this forces SQLite to materialize all columns for all rows. Yuck.

Perhaps we can special case `orderByConsumed` when the only ordering clause is rowid ascending, since that's the natural ordering anyway. See https://www.sqlite.org/vtab.html#the_xbestindex_method for more info

**Comment by cldellow** [comment]
Ooooh, this is probably also why sqlitebrowser's CPU usage goes through the roof when using it to view a parquet-backed table.

**Comment by cldellow** [comment]
Hacking it in, I can confirm that setting it to true fixes the perf issue in the SQL query and makes viewing pages 2+ in datasette fast.

The first view is still slow -- I wonder if it's reading all the distinct values or something.

**Comment by justinclift** [comment]
> Ooooh, this is probably also why sqlitebrowser's CPU usage goes through the roof when using it to view a parquet-backed table.

Heh Heh Heh, we'll it sounds like it's working at least. :smile:
