### ISSUE TITLE
link boost libraries statically

### ISSUE THREAD

**Issue by cldellow** [cldellow/sqlite-parquet-vtable#15]
The 3 boost libraries (system, regex, filesystem) are the only remaining dynamically linked libraries. For better portability, let's link these statically. That should then make it possible to publish a Maven Central artifact that packages xerial-jdbc with this extension.

**Comment by cldellow** [comment]
...and if we compile them ourselves, we'll be able to use more modern g++. Apparently the ABI changed somewhere along the way from version 5 to version 8, and the stock boost that is in the repositories for Ubuntu 14.04 is on the old ABI. I'm slowly beginning to recall why I hate C++.

**Comment by cldellow** [comment]
```
./bootstrap.sh --with-libraries=regex,filesystem,system
./b2 cxxflags=-fPIC cflags=-fPIC
```

seems to compile just the needed boost libs.

Need to pass `DARROW_BOOST_USE_SHARED=OFF` and `DPARQUET_BOOST_USE_SHARED=OFF` when invoking cmake for arrow and parquet.

**Comment by xhochy** [comment]
The ABI problems you ran into with boost are probably the ones described in https://arrow.apache.org/docs/python/development.html#known-issues
