### ISSUE TITLE
UNIX epoch conversions issue

### ISSUE THREAD

**Issue by marklit** [cldellow/sqlite-parquet-vtable#22]
When I try and extract the date and time from a UNIX epoch it's returning in correct values.

```bash
$ sqlite3
```

```sql
.load ./libparquet

CREATE VIRTUAL TABLE trips USING parquet('parquet/000000_0');

select pickup_datetime, 
       datetime(pickup_datetime, 'unixepoch') 
from trips 
limit 1;
```

```
1240714560000|-1413-03-01 13:07:12
```

1240714560000 should be Sunday, 26 April 2009 02:56:00. Any idea how I could extract the year at the very least? Is there another time extraction function I should be using?

**Comment by cldellow** [comment]
I think that's ms since the epoch and `datetime(..., 'unixepoch')` wants seconds -- try dividing `pickup_datetime` by 1000 first?

**Comment by marklit** [comment]
Good spot, works a treat now.
