### ISSUE TITLE
don't needlessly rebuild the compression libraries

### ISSUE THREAD

**Issue by cldellow** [cldellow/sqlite-parquet-vtable#27]
Arrow will download and build the compression libraries (lz4, snappy, zlib, zstd, brotli).

And then we'll do it, too, because we want to compile the static libs with -fPIC.

I think we can opt out of this by passing the right flag to arrow's cmake and setting the appropriate flags in https://github.com/apache/arrow/blob/master/cpp/thirdparty/README.md

**Comment by xhochy** [comment]
Arrow also builds them with `-fPIC` so you could also use its builds. Otherwise setting the `*_HOME` variables will tell Arrow to pick up your builds.

**Comment by cldellow** [comment]
Ah, thank you! That's much preferable.

PS - thank you and all the other arrow/parquet committers for providing these libraries, they're fantastic.
